#!/bin/bash

source test.sh
source utils.sh

# -- SETUP ------------------------------------------------------------------------------#
# ADJUST PATH TO PIPEX DIRECTORY IF NECESSARY (-> IF ITS NOT THE PARENT DIRCTORY)
PIPEX_DIR=$(dirname "$0")/../

TIMEOUT=7
rm -rf outfiles
mkdir outfiles
echo -n > last_err_log.txt

tester_setup

# -- TEST -------------------------------------------------------------------------------#
print_header "BASIC CHECKS"
test "infiles/basic.txt" "cat -e" "cat -e" "outfiles/outfile"
test "infiles/basic.txt" "cat -e" "awk '{print \$1}'" "outfiles/outfile"
test "infiles/basic.txt" "ls -la" "cat -e" "outfiles/outfile"
test "infiles/basic.txt" "ls -l -a" "cat -e -n" "outfiles/outfile"
test "infiles/basic.txt" "ls -l -a -f" "cat -e -n" "outfiles/outfile"
test "infiles/basic.txt" "ls -laf" "cat -e -n" "outfiles/outfile"
test "infiles/basic.txt" "grep -A5 is" "cat -e" "outfiles/nonexistingfile"
test "infiles/basic.txt" "cat -e" "grep nonexistingword" "outfiles/nonexistingfile"
test "infiles/empty.txt" "grep nonexistingword" "cat -e" "outfiles/outfile"
test "infiles/basic.txt" "sleep 3" "ls" "outfiles/outfile"
test "infiles/big_text.txt" "cat" "head -2" "outfiles/outfile"

print_header "ERROR CHECKING"
# invalid input file
test "nonexistingfile" "cat -e" "ls" "outfiles/outfile"
test "nonexistingfile" "cat" "sleep 3" "outfiles/outfile"
touch infiles/infile_without_permissions
chmod 000 infiles/infile_without_permissions
	test "infiles/infile_without_permissions" "cat -e" "cat -e" "outfiles/outfile"
# ouput file without permissions
touch outfiles/outfile_without_permissions
chmod 000 outfiles/outfile_without_permissions
	test "infiles/basic.txt" "cat -e" "cat -e" "outfiles/outfile_without_permissions"
	test "infiles/basic.txt" "sleep 3" "cat -e" "outfiles/outfile_without_permissions"
	test "nonexistingfile" "cat -e" "cat -e" "outfiles/outfile_without_permissions"
# wrong argument
test "infiles/basic.txt" "nonexistingcommand" "cat -e" "outfiles/outfile"
test "infiles/basic.txt" "cat -e" "nonexistingcommand" "outfiles/outfile"

test "infiles/basic.txt" "" "cat -e" "outfiles/outfile"
test "infiles/basic.txt" "cat -e" "" "outfiles/outfile"
test "infiles/basic.txt" "" "sleep 1" "outfiles/outfile"
test "infiles/basic.txt" "sleep 1" "" "outfiles/outfile"
test "infiles/basic.txt" "nonexistingcommand" "sleep 1" "outfiles/outfile"
test "infiles/basic.txt" "sleep 1" "nonexistingcommand" "outfiles/outfile"

test "infiles/basic.txt" "cat -e" "cat -nonexistingflag" "outfiles/outfile"
LEAKS_ONLY=1 # checks only for Leaks (FATAL ERRORS like segfaults are always checked)
	# not enough arguments
	test
	test ""
	test "infiles/basic.txt" "cat -e" "outfiles/outfile"
LEAKS_ONLY=0
	# empty string
	test "" "cat -e" "cat -e" "outfiles/outfile"
	test "infiles/basic.txt" "" "cat -e" "outfiles/outfile"
	test "infiles/basic.txt" "cat -e" "" "outfiles/outfile"
#LEAKS_ONLY=0

print_header "BONUS"

print_header "BONUS WC, CAT, SLEEP, GREP, NONEXISTINGCOMMAD, NOCMD"
# bonus "infiles/basic.txt" "cat -e" "grep pattern" "wc -l" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -i 'hello'" "cat -n" "wc -w" "outfiles/outfile"
bonus "infiles/basic.txt" "wc -c" "cat -e" "sleep 1" "outfiles/outfile"
# bonus "infiles/basic.txt" "sleep 1" "grep -v 'error'" "wc -l" "outfiles/outfile"
# bonus "infiles/basic.txt" "nocmd" "cat -b" "grep 'test'" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -r 'main'" "wc -m" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -n" "grep 'done'" "nonexistingcommand" "outfiles/outfile"
bonus "infiles/basic.txt" "wc -l" "sleep 1" "grep 'TODO'" "outfiles/outfile"
# bonus "infiles/basic.txt" "sleep 1" "cat -e" "grep -c 'test'" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "grep -H 'pattern'" "nocmd" "outfiles/outfile"
bonus "infiles/basic.txt" "nonexistingcommand" "cat -n" "grep 'error'" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -i 'note'" "sleep 1" "wc -w" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "grep -l 'example'" "cat -e" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -v 'ignore'" "cat -e" "wc -l" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -c 'line'" "nonexistingcommand" "cat -e" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -e" "grep -H 'pattern'" "sleep 1" "outfiles/outfile"
# bonus "infiles/basic.txt" "wc -m" "grep 'test'" "nocmd" "outfiles/outfile"
bonus "infiles/basic.txt" "grep 'data'" "cat -e" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "grep 'error'" "cat -e" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -r 'search'" "cat -e" "wc -l" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -n" "grep -i 'find'" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -v 'skip'" "cat -e" "nonexistingcommand" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -c 'count'" "sleep 1" "cat -e" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "grep -H 'match'" "nocmd" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "cat -e" "grep 'line'" "outfiles/outfile"
# bonus "infiles/basic.txt" "wc -l" "grep -v 'ignore'" "cat -e" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep 'pattern'" "nonexistingcommand" "cat -e" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "grep -i 'case'" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "grep 'word'" "cat -e" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -H 'key'" "cat -e" "wc -w" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "grep -r 'value'" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "grep 'record'" "wc -c" "nonexistingcommand" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -i 'tag'" "cat -e" "sleep 1" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -n" "grep -v 'exclude'" "wc -m" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -c 'entry'" "cat -e" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "wc -l" "grep 'query'" "nonexistingcommand" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "grep -r 'item'" "nocmd" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep 'content'" "cat -e" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "grep 'object'" "cat -e" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "grep 'detail'" "wc -m" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -i 'topic'" "sleep 1" "cat -e" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "grep -c 'mention'" "cat -e" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -H 'reference'" "cat -e" "wc -l" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -n" "grep -r 'note'" "sleep 1" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep 'summary'" "cat -e" "wc -w" "outfiles/outfile"
bonus "infiles/basic.txt" "grep 'tag'" "nonexistingcommand" "cat -e" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -e" "grep -i 'point'" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "grep 'info'" "cat -e" "wc -m" "outfiles/outfile"
bonus "infiles/basic.txt" "grep 'line'" "cat -e" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "outfiles/outfile"

print_header "BONUS SLEEP, SLEEP"
bonus "infiles/basic.txt" "sleep 0" "sleep 1" "sleep 2" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 0" "sleep 1" "" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 0" "sleep 2" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 0" "sleep 2" "" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 0" "" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 0" "" "sleep 2" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "sleep 0" "sleep 2" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "sleep 0" "" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "sleep 2" "sleep 0" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "sleep 2" "" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "" "sleep 0" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "" "sleep 2" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 2" "sleep 0" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 2" "sleep 0" "" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 2" "sleep 1" "sleep 0" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 2" "sleep 1" "" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 2" "" "sleep 0" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 2" "" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "" "sleep 0" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "" "sleep 0" "sleep 2" "outfiles/outfile"
bonus "infiles/basic.txt" "" "sleep 1" "sleep 0" "outfiles/outfile"
bonus "infiles/basic.txt" "" "sleep 1" "sleep 2" "outfiles/outfile"
bonus "infiles/basic.txt" "" "sleep 2" "sleep 0" "outfiles/outfile"
bonus "infiles/basic.txt" "" "sleep 2" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 0" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 2" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "sleep 0" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "sleep 1" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "sleep 2" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "" "sleep 0" "outfiles/outfile"
bonus "infiles/basic.txt" "" "" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "" "" "sleep 2" "outfiles/outfile"

# param "" is not first and/or not last
print_header "BONUS ERROR CHECKING 1"
bonus "infiles/basic.txt" "" "" "wc -l" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -i 'hello'" "" "wc -w" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "cat -e" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "grep -v 'error'" "wc -l" "outfiles/outfile"
bonus "infiles/basic.txt" "nocmd" "" "grep 'test'" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -r 'main'" "wc -m" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "" "grep 'done'" "outfiles/outfile"
bonus "infiles/basic.txt" "wc -l" "" "grep 'TODO'" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "cat -e" "" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "" "grep -c 'test'" "outfiles/outfile"
bonus "infiles/basic.txt" "" "" "grep 'error'" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "sleep 1" "wc -w" "outfiles/outfile"
# bonus "infiles/basic.txt" "sleep 1" "grep -l 'example'" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "cat -e" "" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -c 'line'" "" "cat -e" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "wc -m" "" "nocmd" "outfiles/outfile"
bonus "infiles/basic.txt" "grep 'data'" "" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "grep 'error'" "" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -r 'search'" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -n" "" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -v 'skip'" "" "nonexistingcommand" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -c 'count'" "" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "grep -H 'match'" "" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "" "grep 'line'" "outfiles/outfile"
bonus "infiles/basic.txt" "wc -l" "" "cat -e" "outfiles/outfile"
bonus "infiles/basic.txt" "grep 'pattern'" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "" "sleep 1" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "grep 'word'" "" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -H 'key'" "" "wc -w" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "grep -r 'value'" "" "outfiles/outfile"
bonus "infiles/basic.txt" "grep 'record'" "" "nonexistingcommand" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -i 'tag'" "" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "grep -v 'exclude'" "" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -c 'entry'" "" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "wc -l" "" "nonexistingcommand" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "" "nocmd" "outfiles/outfile"
bonus "infiles/basic.txt" "grep 'content'" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "grep 'detail'" "" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -i 'topic'" "" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "grep -c 'mention'" "" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -H 'reference'" "" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "grep -r 'note'" "" "outfiles/outfile"
bonus "infiles/basic.txt" "grep 'summary'" "" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "grep 'tag'" "" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "" "sleep 1" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "grep 'info'" "" "outfiles/outfile"
bonus "infiles/basic.txt" "grep 'line'" "" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "outfiles/outfile"
bonus "infiles/basic.txt" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "" "cat -e" "outfiles/outfile"

# first and/or last param is ""
print_header "BONUS ERROR CHECKING 2"
# bonus "infiles/basic.txt" "" "" "wc -l" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -i 'hello'" "" "wc -w" "outfiles/outfile"
bonus "infiles/basic.txt" "" "cat -e" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "grep -v 'error'" "wc -l" "outfiles/outfile"
# bonus "infiles/basic.txt" "nocmd" "" "grep 'test'" "outfiles/outfile"
bonus "infiles/basic.txt" "grep -r 'main'" "wc -m" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "" "grep 'done'" "outfiles/outfile"
# bonus "infiles/basic.txt" "wc -l" "" "grep 'TODO'" "outfiles/outfile"
bonus "infiles/basic.txt" "" "cat -e" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -e" "" "grep -c 'test'" "outfiles/outfile"
# bonus "infiles/basic.txt" "" "" "grep 'error'" "outfiles/outfile"
bonus "infiles/basic.txt" "" "sleep 1" "wc -w" "outfiles/outfile"
bonus "infiles/basic.txt" "sleep 1" "grep -l 'example'" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "cat -e" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -c 'line'" "" "cat -e" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -e" "" "sleep 1" "outfiles/outfile"
# bonus "infiles/basic.txt" "wc -m" "" "nocmd" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep 'data'" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "grep 'error'" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -r 'search'" "" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -n" "" "sleep 1" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -v 'skip'" "" "nonexistingcommand" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -c 'count'" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "grep -H 'match'" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "sleep 1" "" "grep 'line'" "outfiles/outfile"
# bonus "infiles/basic.txt" "wc -l" "" "cat -e" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep 'pattern'" "" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -e" "" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "" "grep 'word'" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -H 'key'" "" "wc -w" "outfiles/outfile"
bonus "infiles/basic.txt" "" "grep -r 'value'" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep 'record'" "" "nonexistingcommand" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -i 'tag'" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "grep -v 'exclude'" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -c 'entry'" "" "sleep 1" "outfiles/outfile"
# bonus "infiles/basic.txt" "wc -l" "" "nonexistingcommand" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -e" "" "nocmd" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep 'content'" "" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "sleep 1" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "grep 'detail'" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -i 'topic'" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "grep -c 'mention'" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep -H 'reference'" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "grep -r 'note'" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep 'summary'" "" "" "outfiles/outfile"
bonus "infiles/basic.txt" "" "grep 'tag'" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -e" "" "sleep 1" "outfiles/outfile"
bonus "infiles/basic.txt" "" "grep 'info'" "" "outfiles/outfile"
# bonus "infiles/basic.txt" "grep 'line'" "" "sleep 1" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -e" "" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "outfiles/outfile"
# bonus "infiles/basic.txt" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "cat -e" "" "cat -e" "outfiles/outfile"

print_header "BONUS HERE_DOC"
HERE_DOC=$'Hello\nHello\nHello\nEOF\n'
bonus "here_doc" "EOF" "cat -e" "cat -e" "outfiles/outfile"

# 100 times ""
bonus "here_doc" "EOF" "cat -e" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "" "outfiles/outfile"
# 100 times nocmd
bonus "here_doc" "EOF" "cat -e" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "nocmd" "outfiles/outfile"

bonus "here_doc" "EOF" "cat -e" "cat -e" "" "cat -e" "" "outfiles/outfile"
bonus "here_doc" "EOF" "cat -e" "cat -e" "" "outfiles/outfile"
bonus "here_doc" "EOF" "cat -e" "" "cat -e" "outfiles/outfile"
bonus "here_doc" "EOF" "" "cat -e" "cat -e" "outfiles/outfile"
bonus "here_doc" "EOF" "cat -e" "cat -e" "cat -e" "cat -e" "" "outfiles/outfile"
bonus "here_doc" "EOF" "grep no" "cat -e" "" "cat -e" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOF" "grep no" "cat -e" "grep $" "cat -e" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOF" "grep Hello" "cat -e" "grep $" "cat -e" "sleep 2" "nocmd" "outfiles/outfile"
bonus "here_doc" "END" "cat -e" "cat -e" "outfiles/outfile"
bonus "here_doc" "END" "cat -e" "cat -e" "" "cat -e" "" "outfiles/outfile"

print_header "BONUS HERE_DOC ERROR CHECKING"
bonus "here_doc" "EOF" "grep no" "cat -e" "" "cat -e" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOF" "grep no" "cat -e" "grep $" "cat -e" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOF" "grep Hello" "cat -e" "grep $" "cat -e" "sleep 2" "nocmd" "outfiles/outfile"
bonus "here_doc" "END" "cat -e" "cat -e" "outfiles/outfile"
bonus "here_doc" "END" "cat -e" "cat -e" "" "cat -e" "" "outfiles/outfile"
bonus "here_doc" "EOF" "wc -l" "grep error" "cat -n" "" "sleep 1" "outfiles/outfile"
bonus "here_doc" "END" "grep success" "cat -e" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOF" "sleep 1" "" "grep test" "cat -e" "outfiles/outfile"
bonus "here_doc" "EOF" "nocmd" "grep warning" "cat -e" "outfiles/outfile"
bonus "here_doc" "END" "grep fatal" "wc -c" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOF" "grep hello" "" "grep $" "cat -e" "sleep 1" "outfiles/outfile"
bonus "here_doc" "END" "cat -e" "" "wc -w" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOF" "grep world" "nocmd" "cat -e" "outfiles/outfile"
bonus "here_doc" "END" "sleep 1" "grep no" "" "cat -e" "outfiles/outfile"
bonus "here_doc" "EOF" "grep yes" "cat -e" "sleep 2" "" "outfiles/outfile"
bonus "here_doc" "EOF" "wc -m" "grep error" "" "sleep 2" "outfiles/outfile"
bonus "here_doc" "END" "grep warning" "" "grep no" "sleep 1" "cat -e" "outfiles/outfile"
bonus "here_doc" "EOF" "cat -e" "wc -c" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOF" "" "grep test" "cat -e" "nocmd" "outfiles/outfile"
bonus "here_doc" "END" "grep hello" "" "cat -e" "sleep 1" "outfiles/outfile"
bonus "here_doc" "EOF" "grep world" "cat -e" "sleep 2" "outfiles/outfile"
bonus "here_doc" "END" "grep warning" "" "wc -l" "cat -e" "outfiles/outfile"
bonus "here_doc" "EOF" "sleep 2" "grep success" "cat -e" "outfiles/outfile"
bonus "here_doc" "END" "grep fatal" "cat -e" "" "sleep 1" "outfiles/outfile"
bonus "here_doc" "EOF" "grep hello" "cat -e" "sleep 2" "nocmd" "outfiles/outfile"

print_header "BONUS HERE_DOC LIMITER ERROR CHECKING"
bonus "here_doc" "EOFS" "grep no" "cat -e" "" "cat -e" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOFS" "grep no" "cat -e" "grep $" "cat -e" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOFS" "grep Hello" "cat -e" "grep $" "cat -e" "sleep 2" "nocmd" "outfiles/outfile"
bonus "here_doc" "ENDS" "cat -e" "cat -e" "outfiles/outfile"
bonus "here_doc" "ENDS" "cat -e" "cat -e" "" "cat -e" "" "outfiles/outfile"
bonus "here_doc" "EOFS" "wc -l" "grep error" "cat -n" "" "sleep 1" "outfiles/outfile"
bonus "here_doc" "ENDS" "grep success" "cat -e" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOFS" "sleep 1" "" "grep test" "cat -e" "outfiles/outfile"
bonus "here_doc" "EOFS" "nocmd" "grep warning" "cat -e" "outfiles/outfile"
bonus "here_doc" "ENDS" "grep fatal" "wc -c" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOFS" "grep hello" "" "grep $" "cat -e" "sleep 1" "outfiles/outfile"
bonus "here_doc" "ENDS" "cat -e" "" "wc -w" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOFS" "grep world" "nocmd" "cat -e" "outfiles/outfile"
bonus "here_doc" "ENDS" "sleep 1" "grep no" "" "cat -e" "outfiles/outfile"
bonus "here_doc" "EOFS" "grep yes" "cat -e" "sleep 2" "" "outfiles/outfile"
bonus "here_doc" "EOFS" "wc -m" "grep error" "" "sleep 2" "outfiles/outfile"
bonus "here_doc" "ENDS" "grep warning" "" "grep no" "sleep 1" "cat -e" "outfiles/outfile"
bonus "here_doc" "EOFS" "cat -e" "wc -c" "sleep 2" "outfiles/outfile"
bonus "here_doc" "EOFS" "" "grep test" "cat -e" "nocmd" "outfiles/outfile"
bonus "here_doc" "ENDS" "grep hello" "" "cat -e" "sleep 1" "outfiles/outfile"
bonus "here_doc" "EOFS" "grep world" "cat -e" "sleep 2" "outfiles/outfile"
bonus "here_doc" "ENDS" "grep warning" "" "wc -l" "cat -e" "outfiles/outfile"
bonus "here_doc" "EOFS" "sleep 2" "grep success" "cat -e" "outfiles/outfile"
bonus "here_doc" "ENDS" "grep fatal" "cat -e" "" "sleep 1" "outfiles/outfile"
bonus "here_doc" "EOFS" "grep hello" "cat -e" "sleep 2" "nocmd" "outfiles/outfile"

# -- ERROR_OUTPUT -----------------------------------------------------------------------#
if [ "$1" != --hide-errors ]; then print_err_log; fi
